import { Member, OccasionEvent, IncomeTransaction, ExpenseTransaction, CurrentUser, EventGalleryImage, MemberSuggestion, Poll } from './types';


export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'm-admin',
    memberCode: 'M-100',
    fullName: 'सिस्टम ॲडमिन',
    designation: 'ॲडमिन',
    phone: '9822010100',
    annualTargetAmount: 0,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1985-01-01',
    email: 'moryagroupdata@gmail.com',
    age: 41,
    password: 'Tom&jerry5633#',
  },
  // 6 Office Bearers (पदाधिकारी)
  {
    id: 'm-101',
    memberCode: 'M-101',
    fullName: 'राकेश पोटे',
    designation: 'अध्यक्ष',
    phone: '9822010101',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1990-05-15',
    email: 'rakesh.pote@moryagroup.org',
    age: 36,
  },
  {
    id: 'm-102',
    memberCode: 'M-102',
    fullName: 'विजय जगताप',
    designation: 'उपाध्यक्ष',
    phone: '9822010102',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1992-03-10',
    email: 'vijay.jagtap@moryagroup.org',
    age: 34,
  },
  {
    id: 'm-106',
    memberCode: 'M-103',
    fullName: 'प्रशांत सुरेकर',
    designation: 'कार्याध्यक्ष',
    phone: '9822010106',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1988-11-20',
    email: 'prashant.surekar@moryagroup.org',
    age: 37,
  },
  {
    id: 'm-103',
    memberCode: 'M-104',
    fullName: 'धनंजय इंगळे',
    designation: 'सचिव',
    phone: '9822010103',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1991-08-25',
    email: 'dhananjay.ingle@moryagroup.org',
    age: 35,
  },
  {
    id: 'm-104',
    memberCode: 'M-105',
    fullName: 'संकेत कौले',
    designation: 'खजिनदार',
    phone: '9822010104',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1993-01-12',
    email: 'sanket.kaule@moryagroup.org',
    age: 33,
  },
  {
    id: 'm-105',
    memberCode: 'M-106',
    fullName: 'उदय हेरवाडे',
    designation: 'उपखजिनदार',
    phone: '9822010105',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1994-07-08',
    email: 'uday.herwade@moryagroup.org',
    age: 32,
  },
  // General Members (सभासद)
  {
    id: 'm-107',
    memberCode: 'M-107',
    fullName: 'महेश शिंदे',
    designation: 'सभासद',
    phone: '9822010107',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1995-09-18',
    email: 'mahesh.shinde@moryagroup.org',
    age: 31,
  },
  {
    id: 'm-108',
    memberCode: 'M-108',
    fullName: 'अंशुमन वाघमारे',
    designation: 'सभासद',
    phone: '9822010108',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1996-04-05',
    email: 'anshuman.waghmare@moryagroup.org',
    age: 30,
  },
  {
    id: 'm-109',
    memberCode: 'M-109',
    fullName: 'आदित्य मोरगावकर',
    designation: 'सभासद',
    phone: '9822010109',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1997-12-30',
    email: 'aditya.morgaonkar@moryagroup.org',
    age: 28,
  },
  {
    id: 'm-110',
    memberCode: 'M-110',
    fullName: 'किशोर गार्डी',
    designation: 'सभासद',
    phone: '9822010110',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1992-06-14',
    email: 'kishor.gardi@moryagroup.org',
    age: 34,
  },
  {
    id: 'm-111',
    memberCode: 'M-111',
    fullName: 'शशी रजपूत',
    designation: 'सभासद',
    phone: '9822010111',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-112',
    memberCode: 'M-112',
    fullName: 'सनी रजपुत',
    designation: 'सभासद',
    phone: '9822010112',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-113',
    memberCode: 'M-113',
    fullName: 'नितीन कौले',
    designation: 'सभासद',
    phone: '9822010113',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-114',
    memberCode: 'M-114',
    fullName: 'गिरीष ताकवले',
    designation: 'सभासद',
    phone: '9822010114',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-115',
    memberCode: 'M-115',
    fullName: 'शुभम चोरगे',
    designation: 'सभासद',
    phone: '9822010115',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-116',
    memberCode: 'M-116',
    fullName: 'सचिन कांबळे',
    designation: 'सभासद',
    phone: '9822010116',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-117',
    memberCode: 'M-117',
    fullName: 'निखिल मिश्रा',
    designation: 'सभासद',
    phone: '9822010117',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-118',
    memberCode: 'M-118',
    fullName: 'आशिष वाघमारे',
    designation: 'सभासद',
    phone: '9822010118',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-119',
    memberCode: 'M-119',
    fullName: 'संग्राम लोंढे',
    designation: 'सभासद',
    phone: '9822010119',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-120',
    memberCode: 'M-120',
    fullName: 'ओंकार मुकडे',
    designation: 'सभासद',
    phone: '9822010120',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-121',
    memberCode: 'M-121',
    fullName: 'साहिल बोंगाने',
    designation: 'सभासद',
    phone: '9822010121',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-122',
    memberCode: 'M-122',
    fullName: 'राहुल शावी',
    designation: 'सभासद',
    phone: '9822010122',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-123',
    memberCode: 'M-123',
    fullName: 'विपूल क्षीरसागर',
    designation: 'सभासद',
    phone: '9822010123',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-124',
    memberCode: 'M-124',
    fullName: 'स्वप्नील मिश्रा',
    designation: 'सभासद',
    phone: '9822010124',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-125',
    memberCode: 'M-125',
    fullName: 'गजानन पिंगळे',
    designation: 'सभासद',
    phone: '9822010125',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-126',
    memberCode: 'M-126',
    fullName: 'अतुल सव्वाशे',
    designation: 'सभासद',
    phone: '9822010126',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-127',
    memberCode: 'M-127',
    fullName: 'गणेश ठुबे',
    designation: 'सभासद',
    phone: '9822010127',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-128',
    memberCode: 'M-128',
    fullName: 'करण शिवरकर',
    designation: 'सभासद',
    phone: '9822010128',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-129',
    memberCode: 'M-129',
    fullName: 'सतीश बारी',
    designation: 'सभासद',
    phone: '9822010129',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-130',
    memberCode: 'M-130',
    fullName: 'समर्थ भावसार',
    designation: 'सभासद',
    phone: '9822010130',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-131',
    memberCode: 'M-131',
    fullName: 'अथर्व लोळे',
    designation: 'सभासद',
    phone: '9822010131',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-132',
    memberCode: 'M-132',
    fullName: 'पार्थ कांबळे',
    designation: 'सभासद',
    phone: '9822010132',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-133',
    memberCode: 'M-133',
    fullName: 'सुयश बनकर',
    designation: 'सभासद',
    phone: '9822010133',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-134',
    memberCode: 'M-134',
    fullName: 'तुषार गोंधळी',
    designation: 'सभासद',
    phone: '9822010134',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
];

export const INITIAL_OCCASIONS: OccasionEvent[] = [];

export const DEFAULT_USER: CurrentUser = {
  name: 'पाहुणा (Guest)',
  role: 'सभासद',
  isLoggedIn: false,
};

export const INITIAL_INCOMES: IncomeTransaction[] = [];

export const INITIAL_EXPENSES: ExpenseTransaction[] = [];

export const INITIAL_EVENT_GALLERY: EventGalleryImage[] = [
  {
    id: 'gal-1',
    title: 'श्री गणेश मूर्ती प्रतिष्ठापना व महाआरती',
    category: 'गणेशोत्सव',
    dateStr: '२०२५-०९-०७',
    imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80',
    description: 'हडपसर गोंधळनगर येथील मोरया ग्रुपच्या मुख्य व्यासपीठावर श्री गणेशाची भावपूर्ण प्रतिष्ठापना व महाआरती.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_ganeshotsav_photos',
    year: '२०२५-२६',
  },
  {
    id: 'gal-2',
    title: 'श्री विसर्जन मिरवणूक व ढोल-ताशा गजर',
    category: 'विसर्जन मिरवणूक',
    dateStr: '२०२५-०९-१७',
    imageUrl: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=800&q=80',
    description: 'अनंत चतुर्दशी निमित्त मोरया ग्रुपचे ढोल-ताशा पथक व भव्य विसर्जन मिरवणूक सोहळा.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_visarjan_photos',
    year: '२०२५-२६',
  },
  {
    id: 'gal-3',
    title: 'भव्य मंडप सुशोभीकरण व आकर्षक रोषणाई',
    category: 'सजावट व रोषणाई',
    dateStr: '२०२५-०९-०६',
    imageUrl: 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?auto=format&fit=crop&w=800&q=80',
    description: 'मंडळाच्या मुख्य प्रवेशद्वारावर व गोंधळनगर चौकात करण्यात आलेली नेत्रदीपक विद्युत रोषणाई.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_decoration_photos',
    year: '२०२५-२६',
  },
  {
    id: 'gal-4',
    title: 'भव्य महाप्रसाद व अन्नदान सेवा',
    category: 'महाप्रसाद',
    dateStr: '२०२५-०९-१२',
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80',
    description: 'सुमारे ५,००० पेक्षा जास्त भाविकांसाठी आयोजित भव्य महाप्रसाद व आपुलकीचे भोजन.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_mahaprasad_photos',
    year: '२०२५-२६',
  },
  {
    id: 'gal-5',
    title: 'रक्तदान व सर्वसाधारण आरोग्य तपासणी शिबीर',
    category: 'सामाजिक उपक्रम',
    dateStr: '२०२५-०९-१०',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=800&q=80',
    description: 'मंडळातर्फे आयोजित भव्य रक्तदान शिबिरात १५१ बाटल्या रक्त संकलन करण्यात आले.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_social_initiatives',
    year: '२०२५-२६',
  },
  {
    id: 'gal-6',
    title: 'श्री सत्यनारायण महापूजा व भक्ती संगीत संध्या',
    category: 'धार्मिक कार्यक्रम',
    dateStr: '२०२५-०९-१४',
    imageUrl: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80',
    description: 'वार्षिक श्री सत्यनारायण महापूजा व स्थानिक भजनी मंडळाची मंत्रमुग्ध भजने.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_religious_events',
    year: '२०२५-२६',
  },
  {
    id: 'gal-7',
    title: 'आनंद मेळावा व क्रीडा स्पर्धा पारितोषिक वितरण',
    category: 'सांस्कृतिक व क्रीडा',
    dateStr: '२०२५-०९-१५',
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80',
    description: 'लहान मुलांच्या रांगोळी, चित्रकला व क्रीडा स्पर्धांच्या विजेत्यांचा गुणगौरव सोहळा.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_cultural_sports',
    year: '२०२५-२६',
  },
  {
    id: 'gal-8',
    title: 'पर्यावरणपूरक स्वच्छता अभियान व वृक्षारोपण',
    category: 'सामाजिक कार्य',
    dateStr: '२०२५-०८-१५',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80',
    description: 'स्वातंत्र्यदिनानिमित्त गोंधळनगर परिसरात स्वच्छता व ५१ रोपांचे वृक्षारोपण.',
    googleDriveUrl: 'https://drive.google.com/drive/folders/morya_social_work',
    year: '२०२५-२६',
  },
];

export const INITIAL_SUGGESTIONS: MemberSuggestion[] = [];

export const INITIAL_POLLS: Poll[] = [
  {
    id: 'poll-101',
    pollNo: 'POLL-2026-001',
    title: 'गणेशोत्सव २०२६: मुख्य मंडप देखावा व सांस्कृतिक थीम निवड',
    description: 'यंदाच्या गणेशोत्सवासाठी मुख्य देखावा कोणता करावा यावर सर्व कार्यकारणी सदस्यांचे मत हवे आहे. अंतिम निर्णयानुसार देखावा कंत्राटदाराशी चर्चा केली जाईल.',
    category: 'उत्सव नियोजन',
    targetAudience: 'COMMITTEE_ONLY',
    options: [
      { id: 'opt-1', text: 'छत्रपती शिवाजी महाराज राज्याभिषेक ३५० वे वर्ष देखावा', color: 'amber' },
      { id: 'opt-2', text: 'अयोध्येतील श्रीराम मंदिर प्रतिकृती देखावा', color: 'orange' },
      { id: 'opt-3', text: 'पर्यावरण व जलसंधारण जनजागृती देखावा', color: 'emerald' },
      { id: 'opt-4', text: 'पारंपरिक विद्युत रोषणाई व भव्य फुलांची आरास', color: 'indigo' },
    ],
    votes: [
      { memberId: 'm-101', memberName: 'राकेश पोटे', memberRole: 'अध्यक्ष', optionId: 'opt-1', votedAt: '2026-08-20T10:00:00.000Z' },
      { memberId: 'm-103', memberName: 'धनंजय इंगळे', memberRole: 'सचिव', optionId: 'opt-1', votedAt: '2026-08-20T11:30:00.000Z' },
      { memberId: 'm-104', memberName: 'संकेत कौले', memberRole: 'खजिनदार', optionId: 'opt-2', votedAt: '2026-08-20T12:15:00.000Z' },
      { memberId: 'm-102', memberName: 'विजय जगताप', memberRole: 'उपाध्यक्ष', optionId: 'opt-1', votedAt: '2026-08-20T14:20:00.000Z' },
      { memberId: 'm-105', memberName: 'उदय हेरवाडे', memberRole: 'उपखजिनदार', optionId: 'opt-3', votedAt: '2026-08-20T15:00:00.000Z' },
    ],
    status: 'सक्रिय',
    createdByMemberId: 'm-101',
    createdByName: 'राकेश पोटे',
    createdByRole: 'अध्यक्ष',
    createdAt: '2026-08-20T09:30:00.000Z',
    expiresAt: '2026-08-30',
    allowChangeVote: true,
  },
  {
    id: 'poll-102',
    pollNo: 'POLL-2026-002',
    title: 'महाप्रसाद महाभोजन: मुख्य मिष्टान्न (Sweet) मेनू निवड',
    description: 'यंदाच्या अनंत चतुर्दशी महाप्रसादासाठी सर्व सभासदांच्या पसंतीनुसार गोड पदार्थाची निवड करायची आहे. सर्व सभासदांनी आपले मत नोंदवावे.',
    category: 'उत्सव नियोजन',
    targetAudience: 'ALL_MEMBERS',
    options: [
      { id: 'opt-1', text: 'गरमागरम गुलाबजाम', color: 'rose' },
      { id: 'opt-2', text: 'शुद्ध तुपातील बुंदी लाडू', color: 'amber' },
      { id: 'opt-3', text: 'केशर बासुंदी व पुरी', color: 'yellow' },
      { id: 'opt-4', text: 'मोतीचूर लाडू', color: 'orange' },
    ],
    votes: [
      { memberId: 'm-101', memberName: 'राकेश पोटे', memberRole: 'अध्यक्ष', optionId: 'opt-3', votedAt: '2026-08-21T09:00:00.000Z' },
      { memberId: 'm-107', memberName: 'अमोल शिंदे', memberRole: 'सभासद', optionId: 'opt-3', votedAt: '2026-08-21T10:15:00.000Z' },
      { memberId: 'm-108', memberName: 'सचिन गायकवाड', memberRole: 'सभासद', optionId: 'opt-1', votedAt: '2026-08-21T11:00:00.000Z' },
      { memberId: 'm-109', memberName: 'रोहित कदम', memberRole: 'सभासद', optionId: 'opt-3', votedAt: '2026-08-21T11:45:00.000Z' },
      { memberId: 'm-110', memberName: 'प्रमोद पाटील', memberRole: 'सभासद', optionId: 'opt-2', votedAt: '2026-08-21T12:30:00.000Z' },
      { memberId: 'm-104', memberName: 'संकेत कौले', memberRole: 'खजिनदार', optionId: 'opt-3', votedAt: '2026-08-21T13:00:00.000Z' },
    ],
    status: 'सक्रिय',
    createdByMemberId: 'm-103',
    createdByName: 'धनंजय इंगळे',
    createdByRole: 'सचिव',
    createdAt: '2026-08-21T08:30:00.000Z',
    expiresAt: '2026-08-28',
    allowChangeVote: true,
  },
  {
    id: 'poll-103',
    pollNo: 'POLL-2026-003',
    title: 'मंडळाचे नवीन ध्वजस्तंभ व स्वागत कमान उभारणी ठराव',
    description: 'गोंधळनगर चौकात मंडळाची कायमस्वरूपी आकर्षक मेटल स्वागत कमान व ध्वजस्तंभ उभारण्याचा प्रस्ताव मंजूर करावा का?',
    category: 'निर्णय / ठराव',
    targetAudience: 'COMMITTEE_ONLY',
    options: [
      { id: 'opt-1', text: 'पूर्णपणे सहमत (मंजूर)', color: 'emerald' },
      { id: 'opt-2', text: 'असहमत (सध्या नको)', color: 'rose' },
      { id: 'opt-3', text: 'पुढील वर्षी विचार करू', color: 'amber' },
    ],
    votes: [
      { memberId: 'm-101', memberName: 'राकेश पोटे', memberRole: 'अध्यक्ष', optionId: 'opt-1', votedAt: '2026-08-15T10:00:00.000Z' },
      { memberId: 'm-102', memberName: 'विजय जगताप', memberRole: 'उपाध्यक्ष', optionId: 'opt-1', votedAt: '2026-08-15T10:05:00.000Z' },
      { memberId: 'm-103', memberName: 'धनंजय इंगळे', memberRole: 'सचिव', optionId: 'opt-1', votedAt: '2026-08-15T10:10:00.000Z' },
      { memberId: 'm-104', memberName: 'संकेत कौले', memberRole: 'खजिनदार', optionId: 'opt-1', votedAt: '2026-08-15T10:15:00.000Z' },
      { memberId: 'm-105', memberName: 'उदय हेरवाडे', memberRole: 'उपखजिनदार', optionId: 'opt-1', votedAt: '2026-08-15T10:20:00.000Z' },
      { memberId: 'm-106', memberName: 'प्रशांत सुरेकर', memberRole: 'कार्याध्यक्ष', optionId: 'opt-1', votedAt: '2026-08-15T10:25:00.000Z' },
    ],
    status: 'निकाली',
    createdByMemberId: 'm-admin',
    createdByName: 'सिस्टम ॲडमिन',
    createdByRole: 'ॲडमिन',
    createdAt: '2026-08-15T09:00:00.000Z',
    expiresAt: '2026-08-18',
    finalDecision: 'सर्व ६ कार्यकारणी सदस्यांच्या १००% बहुमताने कायमस्वरूपी स्वागत कमान व ध्वजस्तंभ उभारण्याचा ठराव एकमुखाने मंजूर करण्यात आला.',
    finalDecisionBy: 'राकेश पोटे (अध्यक्ष)',
    finalDecisionByRole: 'अध्यक्ष',
    finalDecisionAt: '2026-08-18T18:00:00.000Z',
  }
];

