import { Member, OccasionEvent, IncomeTransaction, ExpenseTransaction, CurrentUser, EventGalleryImage } from './types';

export const INITIAL_MEMBERS: Member[] = [
  // 6 Office Bearers (पदाधिकारी)
  {
    id: 'm-101',
    memberCode: 'M-101',
    fullName: 'राकेश पोटे',
    designation: 'अध्यक्ष',
    phone: '9822010101',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1990-05-15',
    email: 'rakesh.pote@moryagroup.org',
    age: 36,
  },
  {
    id: 'm-106',
    memberCode: 'M-102',
    fullName: 'प्रशांत सुरेकर',
    designation: 'कार्याध्यक्ष',
    phone: '9822010106',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1988-11-20',
    email: 'prashant.surekar@moryagroup.org',
    age: 37,
  },
  {
    id: 'm-102',
    memberCode: 'M-103',
    fullName: 'विजय जगताप',
    designation: 'उपाध्यक्ष',
    phone: '9822010102',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1992-03-10',
    email: 'vijay.jagtap@moryagroup.org',
    age: 34,
  },
  {
    id: 'm-103',
    memberCode: 'M-104',
    fullName: 'धनंजय इंगळे',
    designation: 'सचिव',
    phone: '9822010103',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1991-08-25',
    email: 'dhananjay.ingle@moryagroup.org',
    age: 35,
  },
  {
    id: 'm-104',
    memberCode: 'M-105',
    fullName: 'संकेत कौले',
    designation: 'खजिनदार',
    phone: '9822010104',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1993-01-12',
    email: 'sanket.kaule@moryagroup.org',
    age: 33,
  },
  {
    id: 'm-105',
    memberCode: 'M-106',
    fullName: 'उदय हेरवाडे',
    designation: 'उपखजिनदार',
    phone: '9822010105',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1994-07-08',
    email: 'uday.herwade@moryagroup.org',
    age: 32,
  },
  // General Members (सभासद)
  {
    id: 'm-107',
    memberCode: 'M-107',
    fullName: 'महेश शिंदे',
    designation: 'सभासद',
    phone: '9822010107',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1995-09-18',
    email: 'mahesh.shinde@moryagroup.org',
    age: 31,
  },
  {
    id: 'm-108',
    memberCode: 'M-108',
    fullName: 'अंशुमन वाघमारे',
    designation: 'सभासद',
    phone: '9822010108',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1996-04-05',
    email: 'anshuman.waghmare@moryagroup.org',
    age: 30,
  },
  {
    id: 'm-109',
    memberCode: 'M-109',
    fullName: 'आदित्य मोरगावकर',
    designation: 'सभासद',
    phone: '9822010109',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1997-12-30',
    email: 'aditya.morgaonkar@moryagroup.org',
    age: 28,
  },
  {
    id: 'm-110',
    memberCode: 'M-110',
    fullName: 'किशोर गार्डी',
    designation: 'सभासद',
    phone: '9822010110',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
    birthDate: '1992-06-14',
    email: 'kishor.gardi@moryagroup.org',
    age: 34,
  },
  {
    id: 'm-111',
    memberCode: 'M-111',
    fullName: 'शशी रजपूत',
    designation: 'सभासद',
    phone: '9822010111',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-112',
    memberCode: 'M-112',
    fullName: 'सनी रजपुत',
    designation: 'सभासद',
    phone: '9822010112',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-113',
    memberCode: 'M-113',
    fullName: 'नितीन कौले',
    designation: 'सभासद',
    phone: '9822010113',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-114',
    memberCode: 'M-114',
    fullName: 'गिरीष ताकवले',
    designation: 'सभासद',
    phone: '9822010114',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-115',
    memberCode: 'M-115',
    fullName: 'शुभम चोरगे',
    designation: 'सभासद',
    phone: '9822010115',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-116',
    memberCode: 'M-116',
    fullName: 'सचिन कांबळे',
    designation: 'सभासद',
    phone: '9822010116',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-117',
    memberCode: 'M-117',
    fullName: 'निखिल मिश्रा',
    designation: 'सभासद',
    phone: '9822010117',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-118',
    memberCode: 'M-118',
    fullName: 'आशिष वाघमारे',
    designation: 'सभासद',
    phone: '9822010118',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-119',
    memberCode: 'M-119',
    fullName: 'संग्राम लोंढे',
    designation: 'सभासद',
    phone: '9822010119',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-120',
    memberCode: 'M-120',
    fullName: 'ओंकार मुकडे',
    designation: 'सभासद',
    phone: '9822010120',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-121',
    memberCode: 'M-121',
    fullName: 'साहिल बोंगाने',
    designation: 'सभासद',
    phone: '9822010121',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-122',
    memberCode: 'M-122',
    fullName: 'राहुल शावी',
    designation: 'सभासद',
    phone: '9822010122',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-123',
    memberCode: 'M-123',
    fullName: 'विपूल क्षीरसागर',
    designation: 'सभासद',
    phone: '9822010123',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-124',
    memberCode: 'M-124',
    fullName: 'स्वप्नील मिश्रा',
    designation: 'सभासद',
    phone: '9822010124',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-125',
    memberCode: 'M-125',
    fullName: 'गजानन पिंगळे',
    designation: 'सभासद',
    phone: '9822010125',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-126',
    memberCode: 'M-126',
    fullName: 'अतुल सव्वाशे',
    designation: 'सभासद',
    phone: '9822010126',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-127',
    memberCode: 'M-127',
    fullName: 'गणेश ठुबे',
    designation: 'सभासद',
    phone: '9822010127',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-128',
    memberCode: 'M-128',
    fullName: 'करण शिवरकर',
    designation: 'सभासद',
    phone: '9822010128',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-129',
    memberCode: 'M-129',
    fullName: 'सतीश बारी',
    designation: 'सभासद',
    phone: '9822010129',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-130',
    memberCode: 'M-130',
    fullName: 'समर्थ भावसार',
    designation: 'सभासद',
    phone: '9822010130',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-131',
    memberCode: 'M-131',
    fullName: 'अथर्व लोळे',
    designation: 'सभासद',
    phone: '9822010131',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-132',
    memberCode: 'M-132',
    fullName: 'पार्थ कांबळे',
    designation: 'सभासद',
    phone: '9822010132',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-133',
    memberCode: 'M-133',
    fullName: 'सुयश बनकर',
    designation: 'सभासद',
    phone: '9822010133',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
  {
    id: 'm-134',
    memberCode: 'M-134',
    fullName: 'तुषार गोंधळी',
    designation: 'सभासद',
    phone: '9822010134',
    annualTargetAmount: 6000,
    address: 'हडपसर गोंधळनगर, पुणे',
    isActive: true,
  },
];

export const INITIAL_OCCASIONS: OccasionEvent[] = [
  {
    id: 'occ-1',
    name: 'गणेशोत्सव २०२६',
    year: '२०२६-२७',
    startDate: '2026-08-20',
    endDate: '2026-08-31',
    description: 'वार्षिक गणेशोत्सव सोहळा',
  },
  {
    id: 'occ-2',
    name: 'नवरात्रोत्सव २०२६',
    year: '२०२६-२७',
    startDate: '2026-10-10',
    endDate: '2026-10-19',
    description: 'नवरात्र सोहळा व सांस्कृतिक कार्यक्रम',
  },
  {
    id: 'occ-3',
    name: 'शिवजयंती सोहळा',
    year: '२०२६-२७',
    startDate: '2027-02-19',
    endDate: '2027-02-19',
    description: 'छत्रपती शिवाजी महाराज जयंती उत्सव',
  },
];

export const DEFAULT_USER: CurrentUser = {
  name: 'संकेत कौले',
  role: 'खजिनदार',
  phone: '9822010104',
};

export const INITIAL_INCOMES: IncomeTransaction[] = [
  {
    id: 'inc-1001',
    transactionNo: 'MG-2026-001',
    amount: 1000,
    transactionDate: '2026-08-01',
    depositorType: 'सभासद',
    depositorName: 'राकेश पोटे',
    linkedMemberId: 'm-101',
    linkedMemberName: 'राकेश पोटे (M-101)',
    incomeType: 'सभासद वर्गणी',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'वार्षिक वर्गणी पहिला हप्ता',
    paymentMethod: 'UPI',
    paymentReference: 'UPI/9822010101/84920',
    receiptNumber: 'RCP-101',
    notes: 'ऑनलाईन प्राप्त',
    financialYear: '२०२६-२७',
    createdBy: 'संकेत कौले (खजिनदार)',
    createdAt: '2026-08-01T10:30:00',
  },
  {
    id: 'inc-1002',
    transactionNo: 'MG-2026-002',
    amount: 5000,
    transactionDate: '2026-08-02',
    depositorType: 'सभासद',
    depositorName: 'राकेश पोटे',
    linkedMemberId: 'm-101',
    linkedMemberName: 'राकेश पोटे (M-101)',
    incomeType: 'सभासदाकडून अतिरिक्त देणगी',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'महाप्रसादासाठी विशेष देणगी',
    paymentMethod: 'बँक ट्रान्सफर',
    paymentReference: 'NEFT-58392019',
    receiptNumber: 'RCP-102',
    notes: 'वर्गणी व्यतिरिक्त दिलेली देणगी',
    financialYear: '२०२६-२७',
    createdBy: 'संकेत कौले (खजिनदार)',
    createdAt: '2026-08-02T11:15:00',
  },
  {
    id: 'inc-1003',
    transactionNo: 'MG-2026-003',
    amount: 10000,
    transactionDate: '2026-08-03',
    depositorType: 'व्यवसाय / दुकान',
    depositorName: 'ABC Traders',
    incomeType: 'दुकान / व्यवसाय प्रायोजक',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'गणेशोत्सव मुख्य प्रायोजकत्व',
    paymentMethod: 'UPI',
    paymentReference: 'UPI/ABCTR/992810',
    receiptNumber: 'RCP-103',
    notes: 'मुख्य कमानीवर जाहिरात बॅनर लावणे',
    financialYear: '२०२६-२७',
    createdBy: 'संकेत कौले (खजिनदार)',
    createdAt: '2026-08-03T14:20:00',
  },
  {
    id: 'inc-1004',
    transactionNo: 'MG-2026-004',
    amount: 5240,
    transactionDate: '2026-08-03',
    depositorType: 'अज्ञात / नाव न सांगणारे',
    depositorName: 'अज्ञात देणगीदार',
    incomeType: 'सार्वजनिक देणगी',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'सार्वजनिक देणगी पेटीतील जमा',
    paymentMethod: 'रोख',
    receiptNumber: 'RCP-104',
    notes: 'देणगी पेटी मोजणी',
    financialYear: '२०२६-२७',
    createdBy: 'संकेत कौले (खजिनदार)',
    createdAt: '2026-08-03T18:00:00',
  },
  {
    id: 'inc-1005',
    transactionNo: 'MG-2026-005',
    amount: 6000,
    transactionDate: '2026-08-04',
    depositorType: 'सभासद',
    depositorName: 'विजय जगताप',
    linkedMemberId: 'm-102',
    linkedMemberName: 'विजय जगताप (M-102)',
    incomeType: 'सभासद वर्गणी',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'पूर्ण वार्षिक वर्गणी जमा',
    paymentMethod: 'चेक',
    paymentReference: 'Chq No 400192',
    receiptNumber: 'RCP-105',
    notes: 'एचडीएफसी बँक चेक',
    financialYear: '२०२६-२७',
    createdBy: 'संकेत कौले (खजिनदार)',
    createdAt: '2026-08-04T09:45:00',
  }
];

export const INITIAL_EXPENSES: ExpenseTransaction[] = [
  {
    id: 'exp-2001',
    transactionNo: 'EXP-2026-001',
    amount: 8500,
    expenseDate: '2026-08-02',
    recipientType: 'दुकान / Vendor',
    recipientName: 'श्री गणेश डेकोरेटर्स',
    expenseCategory: 'मंडप व सजावट',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'मंडप उभारणी व मखमली सजावट advance',
    description: 'मुख्य स्टेज सजावट व प्रकाशयोजना',
    paymentMethod: 'UPI',
    paymentReference: 'UPI/DEC/847291',
    billNumber: 'BILL-492',
    financialYear: '२०२६-२७',
    approvalStatus: 'मंजूर',
    approvedBy: 'किरण मोरया (अध्यक्ष)',
    approvedByRole: 'अध्यक्ष',
    approvedAt: '2026-08-02T16:00:00',
    createdBy: 'राजेश पाटील (खजिनदार)',
    createdAt: '2026-08-02T12:00:00',
  },
  {
    id: 'exp-2002',
    transactionNo: 'EXP-2026-002',
    amount: 2400,
    expenseDate: '2026-08-03',
    recipientType: 'दुकान / Vendor',
    recipientName: 'राज इलेक्ट्रिक्स',
    expenseCategory: 'वीज व पाणी',
    occasionId: 'occ-1',
    occasionName: 'गणेशोत्सव २०२६',
    reason: 'तात्पुरते वीज कनेक्शन व केबल खरेदी',
    description: 'एमएससीबी तात्पुरता मीटर खर्च व वायर',
    paymentMethod: 'रोख',
    billNumber: 'BILL-1082',
    financialYear: '२०२६-२७',
    approvalStatus: 'प्रलंबित',
    createdBy: 'राजेश पाटील (खजिनदार)',
    createdAt: '2026-08-03T15:30:00',
  }
];

export const INITIAL_EVENT_GALLERY: EventGalleryImage[] = [
  {
    id: 'gal-1',
    title: 'श्री गणेश मूर्ती प्रतिष्ठापना व महाआरती',
    category: 'गणेशोत्सव',
    dateStr: '२०२५-०९-०७',
    imageUrl: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80',
    description: 'हडपसर गोंधळनगर येथील मोरया ग्रुपच्या मुख्य व्यासपीठावर श्री गणेशाची भावपूर्ण प्रतिष्ठापना व महाआरती.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-2',
    title: 'श्री विसर्जन मिरवणूक व ढोल-ताशा गजर',
    category: 'विसर्जन मिरवणूक',
    dateStr: '२०२५-०९-१७',
    imageUrl: 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=800&q=80',
    description: 'अनंत चतुर्दशी निमित्त मोरया ग्रुपचे ढोल-ताशा पथक व भव्य विसर्जन मिरवणूक सोहळा.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-3',
    title: 'भव्य मंडप सुशोभीकरण व आकर्षक रोषणाई',
    category: 'सजावट व रोषणाई',
    dateStr: '२०२५-०९-०६',
    imageUrl: 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?auto=format&fit=crop&w=800&q=80',
    description: 'मंडळाच्या मुख्य प्रवेशद्वारावर व गोंधळनगर चौकात करण्यात आलेली नेत्रदीपक विद्युत रोषणाई.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-4',
    title: 'भव्य महाप्रसाद व अन्नदान सेवा',
    category: 'महाप्रसाद',
    dateStr: '२०२५-०९-१२',
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=800&q=80',
    description: 'सुमारे ५,००० पेक्षा जास्त भाविकांसाठी आयोजित भव्य महाप्रसाद व आपुलकीचे भोजन.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-5',
    title: 'रक्तदान व सर्वसाधारण आरोग्य तपासणी शिबीर',
    category: 'सामाजिक उपक्रम',
    dateStr: '२०२५-०९-१०',
    imageUrl: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=800&q=80',
    description: 'मंडळातर्फे आयोजित भव्य रक्तदान शिबिरात १५१ बाटल्या रक्त संकलन करण्यात आले.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-6',
    title: 'श्री सत्यनारायण महापूजा व भक्ती संगीत संध्या',
    category: 'धार्मिक कार्यक्रम',
    dateStr: '२०२५-०९-१४',
    imageUrl: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80',
    description: 'वार्षिक श्री सत्यनारायण महापूजा व स्थानिक भजनी मंडळाची मंत्रमुग्ध भजने.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-7',
    title: 'आनंद मेळावा व क्रीडा स्पर्धा पारितोषिक वितरण',
    category: 'सांस्कृतिक व क्रीडा',
    dateStr: '२०२५-०९-१५',
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80',
    description: 'लहान मुलांच्या रांगोळी, चित्रकला व क्रीडा स्पर्धांच्या विजेत्यांचा गुणगौरव सोहळा.',
    year: '२०२५-२६',
  },
  {
    id: 'gal-8',
    title: 'पर्यावरणपूरक स्वच्छता अभियान व वृक्षारोपण',
    category: 'सामाजिक कार्य',
    dateStr: '२०२५-०८-१५',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80',
    description: 'स्वातंत्र्यदिनानिमित्त गोंधळनगर परिसरात स्वच्छता व ५१ रोपांचे वृक्षारोपण.',
    year: '२०२५-२६',
  },
];
